### ISSUE TITLE
Many items use Emerald tooltip

### ISSUE THREAD

**Issue by Rafii2198** [pxlpkr/wynnic-elemental-tooltips#1]
Wynntils just got updated to work with Legendary Tooltips, so I installed it back and noticed many items use emerald tooltip
![image](https://github.com/user-attachments/assets/23ef21d9-03fe-4f28-bd20-d4457ad3ae35)
![image](https://github.com/user-attachments/assets/694d7f96-2931-4f4f-926c-3b4cbfb31870)
![image](https://github.com/user-attachments/assets/4c7551b9-763c-4f8b-9548-fc7c22fb7910)

**Comment by pxlpkr** [comment]
Fixed in 1.1.0 due to transition to Rekindled
